# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 500)
        MainWindow.setMinimumSize(QtCore.QSize(320, 500))
        MainWindow.setMaximumSize(QtCore.QSize(350, 500))
        MainWindow.setStyleSheet("background-color: rgb(208, 208, 208);")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(10, 430, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 380, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 380, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_Resta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Resta.setGeometry(QtCore.QRect(250, 380, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Resta.setFont(font)
        self.pushButton_Resta.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.pushButton_Resta.setObjectName("pushButton_Resta")
        self.pushButton_Ac = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Ac.setGeometry(QtCore.QRect(250, 280, 51, 41))
        self.pushButton_Ac.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Ac.setFont(font)
        self.pushButton_Ac.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Ac.setObjectName("pushButton_Ac")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 330, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_Div = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Div.setGeometry(QtCore.QRect(250, 330, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Div.setFont(font)
        self.pushButton_Div.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.pushButton_Div.setObjectName("pushButton_Div")
        self.pushButton_mr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mr.setGeometry(QtCore.QRect(250, 430, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mr.setFont(font)
        self.pushButton_mr.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.pushButton_mr.setObjectName("pushButton_mr")
        self.pushButton_igual = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_igual.setGeometry(QtCore.QRect(70, 430, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_igual.setFont(font)
        self.pushButton_igual.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.pushButton_igual.setObjectName("pushButton_igual")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(70, 280, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(130, 280, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 330, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_Del = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Del.setGeometry(QtCore.QRect(190, 280, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Del.setFont(font)
        self.pushButton_Del.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Del.setObjectName("pushButton_Del")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 380, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_Mult = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Mult.setGeometry(QtCore.QRect(190, 330, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Mult.setFont(font)
        self.pushButton_Mult.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.pushButton_Mult.setObjectName("pushButton_Mult")
        self.pushButton_Suma = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Suma.setGeometry(QtCore.QRect(190, 380, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Suma.setFont(font)
        self.pushButton_Suma.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.pushButton_Suma.setObjectName("pushButton_Suma")
        self.pushButton7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(10, 280, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton7.setFont(font)
        self.pushButton7.setObjectName("pushButton7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 330, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_F = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_F.setGeometry(QtCore.QRect(260, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_F.setFont(font)
        self.pushButton_F.setObjectName("pushButton_F")
        self.pushButton_D = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_D.setGeometry(QtCore.QRect(160, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_D.setFont(font)
        self.pushButton_D.setObjectName("pushButton_D")
        self.pushButton_C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_C.setGeometry(QtCore.QRect(110, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_C.setFont(font)
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_E = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_E.setGeometry(QtCore.QRect(210, 230, 41, 41))
        self.pushButton_E.setMaximumSize(QtCore.QSize(450, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_E.setFont(font)
        self.pushButton_E.setObjectName("pushButton_E")
        self.pushButton_B = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_B.setGeometry(QtCore.QRect(60, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_B.setFont(font)
        self.pushButton_B.setObjectName("pushButton_B")
        self.pushButton_A = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_A.setGeometry(QtCore.QRect(10, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_A.setFont(font)
        self.pushButton_A.setObjectName("pushButton_A")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(10, 160, 41, 41))
        self.pushButton_25.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 110, 41, 41))
        self.pushButton_26.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(10, 60, 41, 41))
        self.pushButton_27.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.pushButton_28.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_28.setObjectName("pushButton_28")
        self.ResultDec = QtWidgets.QLabel(self.centralwidget)
        self.ResultDec.setGeometry(QtCore.QRect(70, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ResultDec.setFont(font)
        self.ResultDec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ResultDec.setText("")
        self.ResultDec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ResultDec.setObjectName("ResultDec")
        self.ResultBin = QtWidgets.QLabel(self.centralwidget)
        self.ResultBin.setGeometry(QtCore.QRect(70, 60, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ResultBin.setFont(font)
        self.ResultBin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ResultBin.setText("")
        self.ResultBin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ResultBin.setObjectName("ResultBin")
        self.ResultOct = QtWidgets.QLabel(self.centralwidget)
        self.ResultOct.setGeometry(QtCore.QRect(70, 110, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ResultOct.setFont(font)
        self.ResultOct.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ResultOct.setText("")
        self.ResultOct.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ResultOct.setObjectName("ResultOct")
        self.ResultHex = QtWidgets.QLabel(self.centralwidget)
        self.ResultHex.setGeometry(QtCore.QRect(70, 160, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ResultHex.setFont(font)
        self.ResultHex.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ResultHex.setText("")
        self.ResultHex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ResultHex.setObjectName("ResultHex")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConversiones = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.actionConversiones.setFont(font)
        self.actionConversiones.setObjectName("actionConversiones")
        self.actionCaculadora = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.actionCaculadora.setFont(font)
        self.actionCaculadora.setObjectName("actionCaculadora")

        self.retranslateUi(MainWindow)
        self.pushButton_Ac.clicked.connect(self.ResultHex.clear)
        self.pushButton_Ac.clicked.connect(self.ResultOct.clear)
        self.pushButton_Ac.clicked.connect(self.ResultBin.clear)
        self.pushButton_Ac.clicked.connect(self.ResultDec.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_Resta.setText(_translate("MainWindow", "-"))
        self.pushButton_Ac.setText(_translate("MainWindow", "AC"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_Div.setText(_translate("MainWindow", "/"))
        self.pushButton_mr.setText(_translate("MainWindow", "+ -"))
        self.pushButton_igual.setText(_translate("MainWindow", "="))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_Del.setText(_translate("MainWindow", "DEL"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_Mult.setText(_translate("MainWindow", "x"))
        self.pushButton_Suma.setText(_translate("MainWindow", "+"))
        self.pushButton7.setText(_translate("MainWindow", "7"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_F.setText(_translate("MainWindow", "F"))
        self.pushButton_D.setText(_translate("MainWindow", "D"))
        self.pushButton_C.setText(_translate("MainWindow", "C"))
        self.pushButton_E.setText(_translate("MainWindow", "E"))
        self.pushButton_B.setText(_translate("MainWindow", "B"))
        self.pushButton_A.setText(_translate("MainWindow", "A"))
        self.pushButton_25.setText(_translate("MainWindow", "HEX"))
        self.pushButton_26.setText(_translate("MainWindow", "OCT"))
        self.pushButton_27.setText(_translate("MainWindow", "BIN"))
        self.pushButton_28.setText(_translate("MainWindow", "DEC"))
        self.actionConversiones.setText(_translate("MainWindow", "Conversiones "))
        self.actionCaculadora.setText(_translate("MainWindow", "Caculadora "))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

